from protonx import ProtonX

client = ProtonX()

import time

start_time = time.time()

for _ in range(100):

    client.embeddings.create(input=[
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!",
        "Tôi yêu Việt Nam đắm say!!! Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!Tôi yêu Việt Nam đắm say!!!"

    ])

end_time = time.time()
print(f"Embedding creation took {end_time - start_time} seconds")


